management:
  info:
    app:
      name: "@project.name@"
      description: "@project.description@"
      version: "@project.version@"
      spring-boot-version: "@project.parent.version@"
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 8081

spring:
  boot:
    admin:
      client:
        url: http://localhost:8080